package com.cnsyear.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2018-03-08T23:57:56.500+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "OrderWsImplService", 
                  wsdlLocation = "http://localhost:8080/day16/orderws?wsdl",
                  targetNamespace = "http://server.cnsyear.com/") 
public class OrderWsImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.cnsyear.com/", "OrderWsImplService");
    public final static QName OrderWsImplPort = new QName("http://server.cnsyear.com/", "OrderWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/day16/orderws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderWsImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/day16/orderws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderWsImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderWsImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderWsImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderWsImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderWs
     */
    @WebEndpoint(name = "OrderWsImplPort")
    public OrderWs getOrderWsImplPort() {
        return super.getPort(OrderWsImplPort, OrderWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWs
     */
    @WebEndpoint(name = "OrderWsImplPort")
    public OrderWs getOrderWsImplPort(WebServiceFeature... features) {
        return super.getPort(OrderWsImplPort, OrderWs.class, features);
    }

}
