package com.cnsyear.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2018-03-08T23:57:56.469+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://server.cnsyear.com/", name = "OrderWs")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderWs {

    @WebMethod
    @RequestWrapper(localName = "getOrderById", targetNamespace = "http://server.cnsyear.com/", className = "com.cnsyear.client.GetOrderById")
    @ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://server.cnsyear.com/", className = "com.cnsyear.client.GetOrderByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.cnsyear.client.Order getOrderById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
