package com.cnsyear.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2018-03-06T23:08:42.080+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "CxfDataTypeImplService", 
                  wsdlLocation = "http://localhost:80/cxf?wsdl",
                  targetNamespace = "http://sevice.cnsyear.com/") 
public class CxfDataTypeImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sevice.cnsyear.com/", "CxfDataTypeImplService");
    public final static QName CxfDataTypeImplPort = new QName("http://sevice.cnsyear.com/", "CxfDataTypeImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:80/cxf?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CxfDataTypeImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:80/cxf?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CxfDataTypeImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CxfDataTypeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfDataTypeImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfDataTypeImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfDataTypeImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CxfDataTypeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CxfDataType
     */
    @WebEndpoint(name = "CxfDataTypeImplPort")
    public CxfDataType getCxfDataTypeImplPort() {
        return super.getPort(CxfDataTypeImplPort, CxfDataType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfDataType
     */
    @WebEndpoint(name = "CxfDataTypeImplPort")
    public CxfDataType getCxfDataTypeImplPort(WebServiceFeature... features) {
        return super.getPort(CxfDataTypeImplPort, CxfDataType.class, features);
    }

}
