package com.cnsyear.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2018-03-10T20:13:29.520+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://server.cnsyear.com/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://server.cnsyear.com/", className = "com.cnsyear.client.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://server.cnsyear.com/", className = "com.cnsyear.client.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
