package com.cnsyear.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2018-03-04T22:46:41.543+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://server.cnsyear.com/", name = "Server")
@XmlSeeAlso({ObjectFactory.class})
public interface Server {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.cnsyear.com/", className = "com.cnsyear.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.cnsyear.com/", className = "com.cnsyear.client.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
