package com.cnsyear.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2018-03-04T22:46:41.565+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "ServiceImplService", 
                  wsdlLocation = "http://127.0.0.1:8888/sayHello?wsdl",
                  targetNamespace = "http://server.cnsyear.com/") 
public class ServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.cnsyear.com/", "ServiceImplService");
    public final static QName ServiceImplPort = new QName("http://server.cnsyear.com/", "ServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8888/sayHello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8888/sayHello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "ServiceImplPort")
    public Server getServiceImplPort() {
        return super.getPort(ServiceImplPort, Server.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "ServiceImplPort")
    public Server getServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ServiceImplPort, Server.class, features);
    }

}
